version: '3.8'

services:
  bitcoin-api:
    build: .
    container_name: bitcoin-prediction-api
    ports:
      - "5001:5001"
    volumes:
      - ./app/models:/app/app/models
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bitcoin-network

networks:
  bitcoin-network:
    driver: bridge 